name       : lyx
version    : 2.1.4
release    : 1
source     :
    - ftp://ftp.lyx.org/pub/lyx/stable/2.1.x/lyx-2.1.4.tar.xz : d13548cf183f2fc241df8121420933702491a7460c78a0ef6dba0e9e438ef32a
license    : GPL-2.0
summary    : LyX document processor
description: |
    LyX is a document processor that encourages an approach to writing based on the structure of your documents (WYSIWYM) and not simply their appearance (WYSIWYG).
builddeps  :
    - pkgconfig(QtCore)
    - pkgconfig(x11)
patterns   :
    - /usr/share/man
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
