name       : lyx
version    : 2.3.1
release    : 9
source     :
    - ftp://ftp.lyx.org/pub/lyx/stable/2.3.x/lyx-2.3.1-2.tar.xz : f5c9450ba196ed9d49fbc573f65b10d1726d16a62453466957aba2a9f6d66f84
license    : GPL-2.0-or-later
summary    : LyX document processor
description: |
    LyX is a document processor that encourages an approach to writing based on the structure of your documents (WYSIWYM) and not simply their appearance (WYSIWYG).
component  : office
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(hunspell)
    - pkgconfig(mythes)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - libboost-devel
rundeps    :
    - texlive
setup      : |
    %configure --with-enchant \
        --with-hunspell \
        --without-included-boost \
        --without-included-mythes \
        --enable-qt5
build      : |
    %make
install    : |
    %make_install

    install -Dm00644 lib/appdata.xml $installdir/usr/share/metainfo/org.lyx.appdata.xml
    install -dm00755 $installdir/usr/share/bash-completion/completions
    ln -s /usr/share/lyx/scripts/bash_completion $installdir/usr/share/bash-completion/completions/lyx
check      : |
    %make check
