name       : lyx
version    : 2.2.1
release    : 2
source     :
    - ftp://ftp.lyx.org/pub/lyx/stable/2.2.x/lyx-2.2.1.tar.xz : db6b722f4526d44e09609adcacb6acef38eb7a11c7cde91ffe0d1d54ef94740f
license    : GPL-2.0
summary    : LyX document processor
description: |
    LyX is a document processor that encourages an approach to writing based on the structure of your documents (WYSIWYM) and not simply their appearance (WYSIWYG).
component  : office
builddeps  :
    - pkgconfig(hunspell)
    - pkgconfig(QtCore)
    - pkgconfig(x11)
    - libboost-devel
patterns   :
    - /usr/share/man
setup      : |
    %configure --with-hunspell \
               --without-included-boost
build      : |
    %make
install    : |
    %make_install
