name       : lyx
version    : 2.3.0
release    : 7
source     :
    - ftp://ftp.lyx.org/pub/lyx/stable/2.3.x/lyx-2.3.0.tar.xz : 310f556adbfafd243f2c17a0be0d22fa50b9b4f7de41e66625cace8ea088b92b
license    : GPL-2.0
summary    : LyX document processor
description: |
    LyX is a document processor that encourages an approach to writing based on the structure of your documents (WYSIWYM) and not simply their appearance (WYSIWYG).
component  : office
builddeps  :
    - pkgconfig(enchant)
    - pkgconfig(hunspell)
    - pkgconfig(mythes)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(x11)
    - libboost-devel
rundeps    :
    - texlive
setup      : |
    %configure --with-enchant \
        --with-hunspell \
        --without-included-boost \
        --without-included-mythes \
        --enable-qt5
build      : |
    %make
install    : |
    %make_install

    install -D -m00644 lib/appdata.xml $installdir/usr/share/metainfo/org.lyx.appdata.xml
    install -d -m00755 $installdir/usr/share/bash-completion/completions
    ln -s /usr/share/lyx/scripts/bash_completion $installdir/usr/share/bash-completion/completions/lyx
check     : |
    %make check
