name       : lyx
version    : 2.2.3
release    : 6
source     :
    - ftp://ftp.lyx.org/pub/lyx/stable/2.2.x/lyx-2.2.3.tar.xz : 4fcaeb7c202472d9ea21bf826fb30541015fef33e7217eda2be2b5d589c82b57
license    : GPL-2.0
summary    : LyX document processor
description: |
    LyX is a document processor that encourages an approach to writing based on the structure of your documents (WYSIWYM) and not simply their appearance (WYSIWYG).
component  : office
builddeps  :
    - pkgconfig(hunspell)
    - pkgconfig(mythes)
    - pkgconfig(Qt5Svg)
    - pkgconfig(x11)
    - libboost-devel
setup      : |
    %configure --with-hunspell \
               --without-included-boost \
               --without-included-mythes \
               --enable-qt5
build      : |
    %make
install    : |
    %make_install
