name       : lyx
version    : 2.2.2
release    : 3
source     :
    - ftp://ftp.lyx.org/pub/lyx/stable/2.2.x/lyx-2.2.2.tar.gz : 7f6a0aeeeb7e9b1405e27394d1b7192e4abebba2491e5d0ffc6a4cb993803a45
license    : GPL-2.0
summary    : LyX document processor
description: |
    LyX is a document processor that encourages an approach to writing based on the structure of your documents (WYSIWYM) and not simply their appearance (WYSIWYG).
component  : office
builddeps  :
    - pkgconfig(hunspell)
    - pkgconfig(QtCore)
    - pkgconfig(x11)
    - libboost-devel
patterns   :
    - /usr/share/man
setup      : |
    %configure --with-hunspell \
               --without-included-boost
build      : |
    %make
install    : |
    %make_install
